INSERT INTO perfil (nombre, estado)
VALUES ('administrador', 1),
       ('usuario', 1);
INSERT INTO categoria (nombre, descripcion)
VALUES ('Abogados', 'breve descripcion'),
       ('Alfareros y ceramistas‎', 'breve descripcion'),
       ('Artesanos‎', 'breve descripcion'),
       ('Astrólogos‎', 'breve descripcion'),
       ('Biólogos‎', 'breve descripcion'),
       ('Bomberos‎', 'breve descripcion'),
       ('Botánicos‎', 'breve descripcion'),
       ('Botánicos por país‎', 'breve descripcion'),
       ('Científicos‎', 'breve descripcion'),
       ('Colaboradores internacionalistas‎', 'breve descripcion'),
       ('Coreógrafos‎', 'breve descripcion'),
       ('Criminólogos‎', 'breve descripcion'),
       ('Criptógrafos‎', 'breve descripcion'),
       ('Diplomáticos‎', 'breve descripcion'),
       ('Directores de moda‎', 'breve descripcion'),
       ('Editores‎', 'breve descripcion'),
       ('Empleados públicos‎', 'breve descripcion'),
       ('Contadores', 'breve descripcion'),
       ('Empresarios‎', 'breve descripcion'),
       ('Exploradores‎', 'breve descripcion'),
       ('Filósofos‎', 'breve descripcion'),
       ('Fiscales‎', 'breve descripcion'),
       ('Fotógrafos‎', 'breve descripcion'),
       ('Funcionarios administrativos‎', 'breve descripcion'),
       ('Geólogos‎', 'breve descripcion'),
       ('Grandes inventores', 'breve descripcion'),
       ('Ingenieros‎', 'breve descripcion'),
       ('Inventores‎', 'breve descripcion'),
       ('Locutores‎', 'breve descripcion'),
       ('Maestros‎', 'breve descripcion'),
       ('Metodólogo‎', 'breve descripcion'),
       ('Militares‎', 'breve descripcion'),
       ('Médicos‎', 'breve descripcion'),
       ('Navegantes‎', 'breve descripcion'),
       ('Ocupaciones deportivas‎', 'breve descripcion'),
       ('Ocupaciones religiosas', 'breve descripcion'),
       ('Periodistas‎', 'breve descripcion'),
       ('Pilotos‎', 'breve descripcion'),
       ('Policías‎', 'breve descripcion'),
       ('Políticos‎', 'breve descripcion'),
       ('Políticos', 'breve descripcion'),
       ('Profesores‎', 'breve descripcion'),
       ('Publicistas‎', 'breve descripcion'),
       ('Químicos‎', 'breve descripcion'),
       ('Radioaficionados‎', 'breve descripcion'),
       ('Sismólogos‎', 'breve descripcion'),
       ('Sociólogos‎', 'breve descripcion'),
       ('Taxidermistas‎', 'breve descripcion'),
       ('Tecnólogos e Ingenieros‎', 'breve descripcion'),
       ('Tipógrafos‎', 'breve descripcion'),
       ('Otros', 'breve descripcion');

INSERT INTO atributo (tipo, estado)
VALUES ('LIKE', 1),
       ('COMMENT', 1),
       ('SHARE', 1);
INSERT INTO distrito (nombre)
VALUES ('Cercado de Lima'),
       ('Ate'),
       ('Barranco'),
       ('Breña'),
       ('Comas'),
       ('Chorrillos'),
       ('El Agustino'),
       ('Jesús María'),
       ('La Molina'),
       ('La Victoria'),
       ('Lince'),
       ('Magdalena del Mar'),
       ('Miraflores'),
       ('Pueblo Libre'),
       ('Puente Piedra'),
       ('Rimac'),
       ('San Isidro'),
       ('Independencia'),
       ('San Juan de Miraflores'),
       ('San Luis'),
       ('San Martin de Porres'),
       ('San Miguel'),
       ('Santiago de Surco'),
       ('Surquillo'),
       ('Villa María del Triunfo'),
       ('San Juan de Lurigancho'),
       ('Santa Rosa'),
       ('Los Olivos'),
       ('San Borja'),
       ('Villa El Savador'),
       ('Santa Anita'),
       ('Cercado Callao'),
       ('Bellavista'),
       ('Carmen de la Legua'),
       ('La Perla'),
       ('La Punta'),
       ('Ventanilla');
